/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        apple: {
          blue: '#0066cc',
          'blue-focus': '#0071e3',
          'blue-dark': '#2997ff',
          ink: '#1d1d1f',
          'ink-muted-80': '#333333',
          'ink-muted-48': '#7a7a7a',
          divider: '#f0f0f0',
          hairline: '#e0e0e0',
          canvas: '#ffffff',
          parchment: '#f5f5f7',
          pearl: '#fafafc',
          'tile-1': '#272729',
          'tile-2': '#2a2a2c',
          'tile-3': '#252527',
          chip: '#d2d2d7',
          'surface-black': '#000000',
        },
      },
      fontFamily: {
        sans: ['"SF Pro Text"', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"SF Pro Display"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'hero': ['56px', { lineHeight: '1.07', letterSpacing: '-0.28px', fontWeight: '600' }],
        'display-lg': ['40px', { lineHeight: '1.1', fontWeight: '600' }],
        'display-md': ['34px', { lineHeight: '1.47', letterSpacing: '-0.374px', fontWeight: '600' }],
        'lead': ['28px', { lineHeight: '1.14', letterSpacing: '0.196px' }],
        'lead-airy': ['24px', { lineHeight: '1.5', fontWeight: '300' }],
        'tagline': ['21px', { lineHeight: '1.19', letterSpacing: '0.231px', fontWeight: '600' }],
        'body': ['17px', { lineHeight: '1.47', letterSpacing: '-0.374px' }],
        'body-strong': ['17px', { lineHeight: '1.24', letterSpacing: '-0.374px', fontWeight: '600' }],
        'caption': ['14px', { lineHeight: '1.43', letterSpacing: '-0.224px' }],
        'fine-print': ['12px', { lineHeight: '1.0', letterSpacing: '-0.12px' }],
        'nav': ['12px', { lineHeight: '1.0', letterSpacing: '-0.12px' }],
        'button-lg': ['18px', { lineHeight: '1.0', fontWeight: '300' }],
      },
      borderRadius: {
        'sm': '8px',
        'md': '11px',
        'lg': '18px',
        'pill': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '17px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'section': '80px',
      },
    },
  },
  plugins: [],
};
