import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      typography: (theme) => ({
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: theme('colors.expo.body'),
            h1: {
              color: theme('colors.expo.ink'),
              fontWeight: '600',
              fontSize: '36px',
              lineHeight: '1.15',
              letterSpacing: '-1.08px',
              marginTop: '0',
              marginBottom: '0.5em',
            },
            h2: {
              color: theme('colors.expo.ink'),
              fontWeight: '600',
              fontSize: '28px',
              lineHeight: '1.2',
              letterSpacing: '-0.84px',
              marginTop: '2em',
              marginBottom: '0.5em',
            },
            h3: {
              color: theme('colors.expo.ink'),
              fontWeight: '600',
              fontSize: '22px',
              lineHeight: '1.25',
              letterSpacing: '-0.5px',
              marginTop: '1.5em',
              marginBottom: '0.5em',
            },
            h4: {
              color: theme('colors.expo.ink'),
              fontWeight: '600',
              fontSize: '18px',
              lineHeight: '1.4',
              marginTop: '1.5em',
              marginBottom: '0.5em',
            },
            code: {
              color: theme('colors.expo.ink'),
              fontWeight: '400',
              backgroundColor: theme('colors.expo.surface-strong'),
              borderRadius: '4px',
              padding: '0.2em 0.4em',
              fontSize: '13px',
            },
            'code::before': { content: '""' },
            'code::after': { content: '""' },
            'pre code': {
              backgroundColor: 'transparent',
              padding: '0',
              borderRadius: '0',
              fontSize: '13px',
              lineHeight: '1.7',
            },
            'blockquote p:first-of-type::before': { content: '""' },
            'blockquote p:last-of-type::after': { content: '""' },
            strong: {
              color: theme('colors.expo.ink'),
              fontWeight: '600',
            },
            a: {
              color: theme('colors.expo.text-link'),
              textDecoration: 'none',
            },
            'a:hover': { textDecoration: 'underline' },
          },
        },
        dark: {
          css: {
            color: theme('colors.expo.on-dark-soft'),
            h1: { color: theme('colors.expo.on-dark') },
            h2: { color: theme('colors.expo.on-dark') },
            h3: { color: theme('colors.expo.on-dark') },
            h4: { color: theme('colors.expo.on-dark') },
            code: {
              color: theme('colors.expo.on-dark'),
              backgroundColor: theme('colors.expo.surface-dark-elevated'),
            },
            strong: { color: theme('colors.expo.on-dark') },
            'pre code': { color: theme('colors.expo.on-dark') },
            a: { color: theme('colors.expo.accent-link-bright') },
          },
        },
      }),
      colors: {
        expo: {
          black: '#000000',
          'black-active': '#1a1a1a',
          'text-link': '#0d74ce',
          'text-link-secondary': '#476cff',
          ink: '#171717',
          body: '#60646c',
          'body-strong': '#171717',
          muted: '#999999',
          'muted-soft': '#cccccc',
          hairline: '#f0f0f3',
          'hairline-soft': '#f5f5f7',
          'hairline-strong': '#dcdee0',
          canvas: '#ffffff',
          'canvas-soft': '#fafafa',
          'surface-card': '#ffffff',
          'surface-strong': '#f0f0f3',
          'surface-dark': '#171717',
          'surface-dark-elevated': '#1a1a1a',
          'on-primary': '#ffffff',
          'on-dark': '#ffffff',
          'on-dark-soft': '#b0b4ba',
          'sky-light': '#cfe7ff',
          'sky-mid': '#a8c8e8',
          'accent-warning': '#ab6400',
          'accent-preview': '#8145b5',
          'accent-link-bright': '#47c2ff',
          'semantic-error': '#eb8e90',
          'semantic-success': '#16a34a',
        },
      },
      fontFamily: {
        sans: ['"Inter"', '-apple-system', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      fontSize: {
        'display-mega': ['64px', { lineHeight: '1.05', letterSpacing: '-1.92px', fontWeight: '600' }],
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-1.44px', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '1.15', letterSpacing: '-1.08px', fontWeight: '600' }],
        'display-md': ['28px', { lineHeight: '1.2', letterSpacing: '-0.84px', fontWeight: '600' }],
        'display-sm': ['22px', { lineHeight: '1.25', letterSpacing: '-0.5px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5' }],
        'body-sm': ['14px', { lineHeight: '1.5' }],
        'caption': ['13px', { lineHeight: '1.4' }],
        'caption-uppercase': ['11px', { lineHeight: '1.4', letterSpacing: '0.88px', fontWeight: '600', textTransform: 'uppercase' }],
        'button': ['14px', { lineHeight: '1.0', fontWeight: '500' }],
        'nav-link': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'code': ['13px', { lineHeight: '1.5' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'xxl': '24px',
        'pill': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'base': '16px',
        'md': '20px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'section': '96px',
      },
      boxShadow: {
        'expo-card': '0 4px 12px rgba(0, 0, 0, 0.04)',
        'expo-card-hover': '0 8px 24px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [typography],
};
